
replicaCount: 1
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
cron: "50 9 * * *"
cronscale: "5"
namespace: "hello-world"
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - fe.rgsndbx.aws.perion.com
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

hpa:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

#resources:
#  limits:
#    cpu: 256m
#    memory: 512Mi
#   requests:
#    cpu: 100m
#    memory: 128Mi
