apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: scale-up
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scale-up
subjects:
- kind: ServiceAccount
  name: scale-up
