apiVersion: scheduler.io/v1alpha1
kind: CronJob
metadata:
  name: scale-up
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scale
            image: siji/kubectl:v1.5.2
            command:
            - kubectl.sh
            - kubectl
            - scale
            - --replicas=5
            - deployment/hello-world-helloworld-chart
          restartPolicy: OnFailure